### ISSUE TITLE
Project won't build

### ISSUE THREAD

**Issue by diondokter** [tweedegolf/kubikey#2]
There are 2 issues:

- Clap beta 5 is out with a breaking change, so a cargo install or cargo update breaks because the beta isn't pinned
- When not updating or ignoring the lockfile, the crate `lexical-core` is set to 0.7.4 which doesn't compile on my compiler version 1.56.

I was able to solve it by removing `lexical-core` from the lock file, which prompted cargo to update it to 0.7.6 which does build.

**Comment by rnijveld** [comment]
I've upgraded all dependencies to newer versions, the project should now build again!
